### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by ackleyd1** [ackleyd1/codelab-stealing-style#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://ravedave.surge.sh/) and meets the following [project](http://lansingcodelab.com/lessons/stealing-style/1) criteria:
- [x] The font size of your name must be at least 70 pixels, so that it's easy to see.
- [x] Use `span` elements to wrap each letter of your name in a different style, like this: `<span>C</span><span>h</span><span>r</span><span>i</span><span>s</span>`
- [x] Use a color picker to steal the colors in [this image](https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Logo_Google_2013_Official.svg/2000px-Logo_Google_2013_Official.svg.png) and use them to make your name the colors of the Google logo.
- [x] Put a shadow around your entire name, using the style around [the calculator here](https://www.google.com/search?q=4+%2B+2). Inspect the calculator in your web browser to figure out what CSS it's using to create that effect.

**Comment by chrisvfritz** [comment]
Very close! The only problem I'm seeing is the missing color from the use of `box-shadow` around Google's calculator, making the color default to absolute black. Note that depending on the layout of Chrome's inspector, the color may overflow to the line below the `0px 1px 4px 0px`.

**Comment by ackleyd1** [comment]
Okay so i put in a rgba value like shown in the google calculator. I made it light green. Does this meet the requirement? Also you'll have to explain that second part to me at CodeLab tonight

**Comment by chrisvfritz** [comment]
It's still not _quite_ right. Google's calculator has a more subtle, gray `box-shadow`, like this:

![Google calculator box-shadow](https://www.dropbox.com/s/y33yjq81dq8g4df/Screenshot%202016-02-01%2016.34.12.png?dl=1)

You're absolutely right that we want to include an `rgba` value, but I think you may be looking in the wrong place, as that's not the value I'm seeing in Chrome's inspector. In a few hours at Code Lab, I'll show you exactly what I'm talking about. :smiley:

**Comment by ackleyd1** [comment]
Fixed

**Comment by chrisvfritz** [comment]
:+1: :tada: :shipit:
